const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=document.body.dataset.page;
const users=["shadowAce","novaSpark","vortexK","lunaCore","axiomX","driftWolf","ionBlade","pixelRex","zeroPulse","mistValen"];
const rarities=[["Mil-Spec",.7992],["Restricted",.1598],["Classified",.032],["Covert",.0064],["Knife",.0026]];
const patterns=["Blue Gem","Doppler","Fade","Tiger Tooth","Crimson Web","Lore","Slaughter","Night","Case Hardened","Emerald","Ruby","Sapphire"];
const guns=["AK-47","M4A1-S","AWP","Glock-18","USP-S","Desert Eagle","FAMAS","P90","MP9","AUG","SG553","Galil AR","MAC-10","MP7","UMP-45","Nova","XM1014","M249","Negev","Five-SeveN","P250","Dual Berettas","CZ75-Auto","Karambit","Butterfly Knife","Bayonet","Talon Knife","Skeleton Knife","Nomad Knife","Flip Knife"];
const cases=[{name:"Revolution",price:2.1,high:false},{name:"Dreams & Nightmares",price:2.2,high:false},{name:"Fracture",price:2.4,high:false},{name:"Clutch",price:2.5,high:false},{name:"Prisma 2",price:2.6,high:false},{name:"Gamma 2",price:2.7,high:false},{name:"Operation High Tier",price:8.5,high:true},{name:"Dragon Vault",price:12,high:true},{name:"Sticker Capsule",price:.9,stickerOnly:true,high:false},{name:"Event Sticker Capsule",price:2.8,stickerOnly:true,high:false}];
const ranks=["Silver I","Silver Elite","Gold Nova","Master Guardian","DMG","Legendary Eagle","Supreme","Global Elite"];
const updates=["2026-02-22 Split app into real pages with sidebar navigation.","2026-02-22 Improved casino stability and visuals.","2026-02-22 Added inventory favorites + autosell + help page."];
const base={user:null,money:300,bank:0,xp:0,level:1,rank:"Silver I",luck:1,perClick:1,auto:0,loyalty:0,streak:0,lastDaily:null,lastWheel:null,event:"None",eventTick:0,inventory:[],favorites:[],history:[],themeMods:{},stats:{opened:0,profit:0,highest:0,games:0,wins:0,losses:0},market:[100,101,98,103],listings:[],pendingBid:null,sortByValue:false,casino:{game:"Blackjack",blackjack:null,crash:null,mines:null,jackpot:{bet:[],bot:[]},coinPick:"heads"}};
const state=Object.assign({},base,JSON.parse(localStorage.getItem("neoncase")||"{}"));
const rnd=(a,b)=>Math.random()*(b-a)+a,m=v=>`$${v.toFixed(2)}`;

function svgData(svg){return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`}
const weaponImg=n=>svgData(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 320 120'><defs><linearGradient id='g' x1='0' x2='1'><stop stop-color='${/Knife|Karambit|Bayonet|Talon|Butterfly/.test(n)?'#98d8ff':'#d9a0ff'}'/><stop offset='1' stop-color='#6945cc'/></linearGradient></defs><rect width='320' height='120' fill='#13182a'/><path d='M24 74 L242 74 L292 58 L242 44 L24 44 Z' fill='url(#g)'/><rect x='220' y='40' width='16' height='38' fill='#21263f'/><text x='10' y='20' fill='white' font-size='13'>${n}</text></svg>`);
const caseImg=n=>svgData(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 220 120'><rect width='220' height='120' rx='12' fill='#1f243b'/><rect x='10' y='10' width='200' height='100' rx='10' fill='#374069'/><rect x='14' y='14' width='192' height='92' rx='8' fill='none' stroke='#91a3e8'/><text x='16' y='64' fill='white' font-size='15'>${n}</text></svg>`);

function save(){localStorage.setItem("neoncase",JSON.stringify(state));renderCommon();renderPage();}
function today(){return new Date().toISOString().slice(0,10)}
function pushHistory(t){state.history.unshift(`${new Date().toLocaleTimeString()} • ${t}`);state.history=state.history.slice(0,120)}
function rollRarity(high=false){let r=Math.random(),s=0,boost=(high?1.2:1)*(state.luck*([0,6].includes(new Date().getDay())?1.2:1));for(const [n,c] of rarities){s+=n==="Knife"?c*boost:c;if(r<=s)return n}return"Mil-Spec"}
const priceByRarity=r=>({"Mil-Spec":1.6,"Restricted":8.4,"Classified":28,"Covert":120,"Knife":700}[r]);
function makeSkin(c){const weapon=guns[Math.floor(rnd(0,guns.length))],rarity=rollRarity(c?.high),pattern=patterns[Math.floor(rnd(0,patterns.length))],float=rnd(.0001,.99).toFixed(4),seed=Math.floor(rnd(1,1000));let value=priceByRarity(rarity)*rnd(.85,1.25)*(c?.high?1.35:1);if(c?.stickerOnly)value=rnd(.2,3.5);return{id:crypto.randomUUID(),weapon:c?.stickerOnly?"Sticker Pack":weapon,rarity:c?.stickerOnly?"Restricted":rarity,pattern:c?.stickerOnly?"Event Stickers":pattern,float,seed,value:+value.toFixed(2),img:weaponImg(weapon),eventLimited:state.event!=="None"&&Math.random()>.84}}
function levelUp(){while(state.xp>=state.level*100){state.xp-=state.level*100;state.level++;state.perClick+=.08;state.luck+=.02}state.rank=ranks[Math.min(ranks.length-1,Math.floor(state.level/6))]}
function applyFx(){const fx=$('#seasonFx');if(!fx)return;fx.className='season-fx';if(state.event==='Christmas')fx.classList.add('christmas');if(state.event==='Halloween')fx.classList.add('halloween');if(state.event==='Summer Heat')fx.classList.add('summer')}

function renderCommon(){if($('#money'))$('#money').textContent=m(state.money);if($('#bankMoney'))$('#bankMoney').textContent=m(state.bank);if($('#rank'))$('#rank').textContent=state.rank;applyFx();}

function renderCases(){const list=$('#caseList');if(!list)return;list.innerHTML=cases.map(c=>`<div class='skin-card ${c.high?'event-border':''}'><div class='case-thumb'><img src='${caseImg(c.name)}'/></div><b>${c.name}</b><div>${m(c.price)}</div><small>Knife odds ~0.26%</small><button onclick='openCase("${c.name}",+document.getElementById("openCount").value||1)'>Open</button></div>`).join('');}
window.openCase=(name,count)=>{const c=cases.find(x=>x.name===name);if(!c)return;const cost=c.price*count;if(state.money<cost)return;state.money-=cost;const anim=$('#caseAnimation');if(anim)anim.innerHTML='Opening...';setTimeout(()=>{const pulls=[];for(let i=0;i<count;i++)pulls.push(makeSkin(c));state.inventory.push(...pulls);state.stats.opened+=count;state.stats.highest=Math.max(state.stats.highest,...pulls.map(p=>p.value));state.money+=pulls.reduce((a,b)=>a+b.value*.03,0);state.xp+=count*8;levelUp();const out=$('#openResults');if(out)out.innerHTML=pulls.map(skinCard).join('');if(pulls.some(x=>x.rarity==='Knife'))pushHistory('✨ Knife pulled!');save();},700)};

function skinCard(s){return `<div class='skin-card rarity-${s.rarity}'><div class='weapon-img'><img src='${s.img}'/></div><b>${s.weapon}</b><small>${s.pattern}</small><div>${m(s.value)}</div><small>Float ${s.float} • Seed ${s.seed}</small><div class='row-wrap'><button onclick='toggleFav("${s.id}")'>${state.favorites.includes(s.id)?'★':'☆'}</button><button onclick='sellSkin("${s.id}")'>Sell</button><button onclick='bankSkin("${s.id}")'>Bank</button></div></div>`}
window.toggleFav=id=>{state.favorites.includes(id)?state.favorites=state.favorites.filter(x=>x!==id):state.favorites.push(id);save()};
window.sellSkin=id=>{const i=state.inventory.findIndex(x=>x.id===id);if(i<0)return;state.money+=state.inventory[i].value;state.inventory.splice(i,1);save()};
window.bankSkin=id=>{const i=state.inventory.findIndex(x=>x.id===id);if(i<0)return;state.bank+=state.inventory[i].value;state.inventory.splice(i,1);save()};

function renderPage(){
  if(page==='dashboard'){ if($('#seasonEvent'))$('#seasonEvent').textContent=state.event==='None'?'No active event right now':`${state.event} active`; if($('#liveFeed'))$('#liveFeed').innerHTML=Array.from({length:10},()=>`<div>${users[Math.floor(rnd(0,users.length))]} pulled ${guns[Math.floor(rnd(0,guns.length))]}</div>`).join(''); if($('#updateLog'))$('#updateLog').innerHTML=updates.map(x=>`<div>${x}</div>`).join(''); }
  if(page==='clicker'){ $('#perClick').textContent=m(state.perClick); $('#xpLevel').textContent=`${state.xp.toFixed(0)}/Lv ${state.level}`; $('#loyalty').textContent=state.loyalty; $('#streak').textContent=state.streak; $('#upgClick').textContent=`Upgrade Click (${m(8+state.perClick*6)})`; $('#upgAuto').textContent=`Upgrade Auto (${m(20+state.auto*14)})`; $('#upgLuck').textContent=`Upgrade Luck (${m(40+state.luck*24)})`; }
  if(page==='cases'){renderCases();}
  if(page==='battles'){ const sel=$('#battleCase'); if(sel)sel.innerHTML=cases.map(c=>`<option>${c.name}</option>`).join(''); }
  if(page==='inventory'){ const rf=$('#rarityFilter').value,q=$('#searchSkin').value.toLowerCase();let inv=state.inventory.filter(s=>(rf==='all'||s.rarity===rf)&&(`${s.weapon} ${s.pattern}`.toLowerCase().includes(q)));if(state.sortByValue)inv=inv.sort((a,b)=>b.value-a.value);$('#inventoryGrid').innerHTML=inv.map(skinCard).join(''); }
  if(page==='database'){ $('#databaseGrid').innerHTML=guns.slice(0,90).flatMap(g=>patterns.slice(0,3).map(p=>`<div class='skin-card'><div class='weapon-img'><img src='${weaponImg(g)}'/></div><b>${g} | ${p}</b></div>`)).join(''); }
  if(page==='stats'){ $('#statsList').innerHTML=`<li>Cases opened: ${state.stats.opened}</li><li>Profit/Loss: ${m(state.stats.profit)}</li><li>Best item: ${m(state.stats.highest)}</li><li>Games: ${state.stats.games} (W ${state.stats.wins}/L ${state.stats.losses})</li>`; }
  if(page==='market'){ renderMarket(); drawGraph(); }
  if(page==='casino'){ buildCasinoUI(); }
}

function drawGraph(){const c=$('#marketGraph');if(!c)return;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#2a3651';x.strokeRect(0,0,c.width,c.height);x.strokeStyle='#cf72ff';x.beginPath();state.market.forEach((v,i)=>{const px=20+i*(c.width-40)/(state.market.length-1),py=c.height-(v-90)*2;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();}
function renderMarket(){const el=$('#marketListings');if(!el)return;el.innerHTML=state.listings.map((l,i)=>`<div class='skin-card'><b>${l.name}</b><div>${m(l.price)}</div><small>${l.type}</small><div class='row-wrap'><button onclick='buyListing(${i})'>Buy</button><button onclick='startBid(${i})'>Bid</button></div></div>`).join('')}
window.buyListing=i=>{const l=state.listings[i];if(!l||state.money<l.price)return;state.money-=l.price;state.inventory.push(makeSkin({high:l.price>6}));state.listings.splice(i,1);save()};
window.startBid=i=>{const l=state.listings[i];if(!l)return;state.pendingBid={index:i,botBids:[+rnd(1,6).toFixed(2),+rnd(2,9).toFixed(2)]};$('#bidItem').textContent=l.name;$('#bidInput').value=(l.price*.6).toFixed(2);$('#bidModal').showModal()};
function confirmBid(){const p=state.pendingBid;if(!p)return;const l=state.listings[p.index];if(!l)return;const my=+$('#bidInput').value;if(state.money<my)return;state.money-=my;$('#bidWheel').style.transform=`rotate(${Math.floor(rnd(900,2200))}deg)`;setTimeout(()=>{const bot=Math.max(...p.botBids,+rnd(1,l.price*1.2).toFixed(2));const chance=Math.min(.9,Math.max(.1,my/(my+bot)));if(Math.random()<chance){state.inventory.push(makeSkin({high:true}));state.listings.splice(p.index,1)}$('#bidModal').close();state.pendingBid=null;save()},5000)}

// casino simple
function buildCasinoUI(){const g=state.casino.game=$('#gameSelect').value,ui=$('#casinoUI'); if(!ui)return;
 if(g==='Blackjack') ui.innerHTML=`<div class='cards'>Dealer: <span id='dCards'></span></div><div class='cards'>You: <span id='pCards'></span></div><div class='row-wrap'><button id='hit'>Hit</button><button id='stand'>Stand</button></div>`;
 if(g==='Roulette') ui.innerHTML=`<div class='row-wrap'><select id='rType'><option value='red'>Red</option><option value='black'>Black</option><option value='even'>Even</option><option value='odd'>Odd</option><option value='number'>Number</option></select><input id='rNum' type='number' min='0' max='36' value='7'/></div>`;
 if(g==='Coinflip') ui.innerHTML=`<div class='row-wrap'><button class='pick ${state.casino.coinPick==='heads'?'active':''}' data-p='heads'>Heads</button><button class='pick ${state.casino.coinPick==='tails'?'active':''}' data-p='tails'>Tails</button><div id='coin' class='coin-art'></div></div>`;
 if(g==='Crash') ui.innerHTML=`<canvas id='crashCanvas' width='1000' height='220'></canvas><div id='crashMult'>1.00x</div><button id='cashCrash'>Cash Out</button>`;
 if(g==='Jackpot') ui.innerHTML=`<div id='jackWheel' style='width:200px;height:200px;border-radius:50%;background:conic-gradient(#8f46ff 0 30%,#ff4bb3 30% 60%,#20c4ff 60% 100%)'></div>`;
 if(g==='Mines') ui.innerHTML=`<div class='row-wrap'><input id='bombs' type='number' min='1' max='20' value='3'/><button id='startMines'>Start</button><button id='cashMines'>Cashout</button><span id='mMult'>1.00x</span></div><div id='mGrid' class='mines-grid'></div>`;
 if(g==='Slots') ui.innerHTML=`<div class='slot-reels'><div id='s1'>A</div><div id='s2'>K</div><div id='s3'>7</div></div>`;
 if(g==='Plinko') ui.innerHTML=`<div id='pBoard' class='plinko-board'></div><button id='dropBall'>Drop Ball</button>`;
 bindCasino(); renderBJ(); if(g==='Mines') renderMines(); if(g==='Crash') drawCrashCanvas(); if(g==='Plinko') setupPlinko();
}
const deck=['A♠','A♥','A♦','A♣','K♠','Q♥','J♦','10♣','9♠','8♥','7♦','6♣','5♠','4♥','3♦','2♣'];
const cv=c=>c.startsWith('A')?11:['K','Q','J','10'].some(x=>c.startsWith(x))?10:+c[0];
const dcard=()=>deck[Math.floor(rnd(0,deck.length))];
function fixA(h){while(h.reduce((a,b)=>a+cv(b),0)>21&&h.some(c=>c.startsWith('A')))h[h.findIndex(c=>c.startsWith('A'))]='1♠'}
const score=h=>h.reduce((a,b)=>a+(b.startsWith('1')?1:cv(b)),0);
function renderBJ(){const bj=state.casino.blackjack;if(!bj||!$('#dCards'))return;$('#dCards').innerHTML=bj.d.map(c=>`<span class='card'>${c}</span>`).join('');$('#pCards').innerHTML=bj.p.map(c=>`<span class='card'>${c}</span>`).join('')}
function bindCasino(){if($('#hit'))$('#hit').onclick=bjHit;if($('#stand'))$('#stand').onclick=bjStand;if($('#cashCrash'))$('#cashCrash').onclick=crashCash;if($('#startMines'))$('#startMines').onclick=minesStart;if($('#cashMines'))$('#cashMines').onclick=minesCash;if($('#dropBall'))$('#dropBall').onclick=plinkoDrop;$$('.pick').forEach(b=>b.onclick=()=>{state.casino.coinPick=b.dataset.p;buildCasinoUI();});}
function playCasino(){const g=state.casino.game,b=+($('#betAmount')?.value||0); if(g==='Blackjack')return bjStart(b); if(g==='Roulette')return roulette(b); if(g==='Coinflip')return coinflip(b); if(g==='Crash')return crashStart(b); if(g==='Jackpot')return jackpot(b); if(g==='Mines')return minesBet(b); if(g==='Slots')return slots(b);}
function bjStart(b){if(state.money<b)return;state.money-=b;state.casino.blackjack={bet:b,p:[dcard(),dcard()],d:[dcard(),dcard()],done:false};fixA(state.casino.blackjack.p);fixA(state.casino.blackjack.d);renderBJ();save()}
function bjHit(){const bj=state.casino.blackjack;if(!bj||bj.done)return;bj.p.push(dcard());fixA(bj.p);renderBJ();if(score(bj.p)>21){bj.done=true;state.stats.games++;state.stats.losses++;state.stats.profit-=bj.bet;save()}}
function bjStand(){const bj=state.casino.blackjack;if(!bj||bj.done)return;while(score(bj.d)<17){bj.d.push(dcard());fixA(bj.d)}bj.done=true;const p=score(bj.p),d=score(bj.d);let pay=0;if(d>21||p>d)pay=bj.bet*2;else if(p===d)pay=bj.bet;state.money+=pay;state.stats.games++;pay>bj.bet?(state.stats.wins++,state.stats.profit+=pay-bj.bet):(state.stats.losses++,state.stats.profit-=bj.bet-pay);renderBJ();save()}
function roulette(b){if(state.money<b)return;state.money-=b;const t=$('#rType')?.value||'red',n=+($('#rNum')?.value||0),land=Math.floor(rnd(0,37)),color=land===0?'green':land%2?'red':'black';let win=false,mult=0;if(['red','black'].includes(t)){win=color===t;mult=2}else if(['even','odd'].includes(t)){win=land!==0&&((land%2?'odd':'even')===t);mult=2}else{win=land===n;mult=36}const pay=win?b*mult:0;state.money+=pay;state.stats.games++;win?(state.stats.wins++,state.stats.profit+=pay-b):(state.stats.losses++,state.stats.profit-=b);save()}
function coinflip(b){if(state.money<b)return;state.money-=b;const r=Math.random()>.5?'heads':'tails';$('#coin')?.classList.add('flip');setTimeout(()=>$('#coin')?.classList.remove('flip'),800);const win=r===state.casino.coinPick,pay=win?b*1.95:0;state.money+=pay;state.stats.games++;win?(state.stats.wins++,state.stats.profit+=pay-b):(state.stats.losses++,state.stats.profit-=b);save()}
function crashStart(b){if(state.money<b)return;state.money-=b;state.casino.crash={bet:b,m:1,active:true,pts:[{x:0,y:220}]};save()}
function drawCrashCanvas(){const c=$('#crashCanvas');if(!c)return;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#2a3651';x.strokeRect(0,0,c.width,c.height);x.strokeStyle='#6eff95';x.beginPath();(state.casino.crash?.pts||[{x:0,y:220}]).forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke();if($('#crashMult'))$('#crashMult').textContent=`${(state.casino.crash?.m||1).toFixed(2)}x`;}
function crashTick(){const c=state.casino.crash;if(!c?.active)return;c.m+=rnd(.01,.06);c.pts.push({x:Math.min(1000,c.pts.at(-1).x+8),y:Math.max(6,220-c.m*18)});if(c.pts.length>120)c.pts.shift();drawCrashCanvas();if(Math.random()>.985||c.m>12){c.active=false;state.stats.games++;state.stats.losses++;state.stats.profit-=c.bet;save()}}
function crashCash(){const c=state.casino.crash;if(!c?.active)return;c.active=false;const pay=c.bet*c.m;state.money+=pay;state.stats.games++;state.stats.wins++;state.stats.profit+=pay-c.bet;save()}
function jackpot(b){if(state.money<b)return;state.money-=b;const chance=Math.min(.9,Math.max(.1,b/(b+10)));$('#jackWheel')?.style.setProperty('transform',`rotate(${Math.floor(rnd(900,2200))}deg)`);setTimeout(()=>{if(Math.random()<chance){state.inventory.push(makeSkin({high:true}));state.stats.wins++}else state.stats.losses++;state.stats.games++;save()},1000)}
function minesBet(b){if(state.money<b)return;state.money-=b;state.casino.mines={bet:b,bombs:3,mult:1,live:false,board:Array(25).fill(false),rev:Array(25).fill('')};buildCasinoUI();}
function renderMines(){const m=state.casino.mines;if(!m||!$('#mGrid'))return;const g=$('#mGrid');g.innerHTML='';for(let i=0;i<25;i++){const b=document.createElement('button');b.className='mine-cell';if(m.rev[i]==='SAFE'){b.classList.add('open');b.textContent='SAFE'}if(m.rev[i]==='X'){b.classList.add('bomb');b.textContent='X'}b.onclick=()=>minePick(i,b);g.appendChild(b)}$('#mMult').textContent=`${m.mult.toFixed(2)}x`;}
function minesStart(){const m=state.casino.mines;if(!m)return;m.bombs=Math.max(1,Math.min(20,+($('#bombs')?.value||3)));m.mult=1;m.live=true;m.board=Array(25).fill(false);m.rev=Array(25).fill('');for(let i=0;i<m.bombs;i++)m.board[Math.floor(rnd(0,25))]=true;renderMines()}
function minePick(i,b){const m=state.casino.mines;if(!m?.live||m.rev[i])return;if(m.board[i]){m.rev[i]='X';m.live=false;state.stats.games++;state.stats.losses++;state.stats.profit-=m.bet}else{m.rev[i]='SAFE';m.mult+=.18+(m.bombs/100)}renderMines();save()}
function minesCash(){const m=state.casino.mines;if(!m?.live)return;m.live=false;const pay=m.bet*m.mult;state.money+=pay;state.stats.games++;state.stats.wins++;state.stats.profit+=pay-m.bet;save()}
function slots(b){if(state.money<b)return;state.money-=b;const sym=['A','K','7','B','C'];let t=0;const id=setInterval(()=>{['s1','s2','s3'].forEach(k=>{const el=$('#'+k);if(el)el.textContent=sym[Math.floor(rnd(0,sym.length))]});if(++t>14){clearInterval(id);const o=['s1','s2','s3'].map(k=>$('#'+k)?.textContent||'A');let mult=0;if(o[0]===o[1]&&o[1]===o[2])mult=5;else if(o[0]===o[1]||o[1]===o[2]||o[0]===o[2])mult=2;const pay=b*mult;state.money+=pay;state.stats.games++;mult?(state.stats.wins++,state.stats.profit+=pay-b):(state.stats.losses++,state.stats.profit-=b);save()}},80)}
function setupPlinko(){const p=$('#pBoard');if(!p)return;p.innerHTML='';for(let r=0;r<10;r++)for(let c=0;c<=r;c++){const d=document.createElement('div');d.className='peg';d.style.left=`${14+c*28+r*6}px`;d.style.top=`${10+r*25}px`;p.appendChild(d)}}
function plinkoDrop(){const b=+($('#betAmount')?.value||0);if(state.money<b)return;state.money-=b;const p=$('#pBoard');if(!p)return;const ball=document.createElement('div');ball.className='plinko-ball';p.appendChild(ball);let x=50,y=0;const id=setInterval(()=>{y+=8;x+=(Math.random()>.5?6:-6);ball.style.left=`${Math.max(5,Math.min(95,x))}%`;ball.style.top=`${y}px`;if(y>250){clearInterval(id);const mult=[0,.5,1,2,5][Math.floor(rnd(0,5))],pay=b*mult;state.money+=pay;state.stats.games++;mult>=1?(state.stats.wins++,state.stats.profit+=pay-b):(state.stats.losses++,state.stats.profit-=b-pay);save()}},55)}

// shared bindings
$('#toggleSidebar')?.addEventListener('click',()=>$('#sidebar').classList.toggle('collapsed'));
$('#openAuth')?.addEventListener('click',()=>$('#authModal').showModal());
$('#closeAuth')?.addEventListener('click',()=>$('#authModal').close());
$('#signup')?.addEventListener('click',()=>{state.user=$('#username').value.trim();save()});
$('#login')?.addEventListener('click',()=>{const u=$('#username').value.trim();if(u){state.user=u;save()}});
$('#logout')?.addEventListener('click',()=>{state.user=null;save()});
$('#themeToggle')?.addEventListener('click',()=>document.documentElement.classList.toggle('light'));
$('#confirmBid')?.addEventListener('click',confirmBid);$('#cancelBid')?.addEventListener('click',()=>$('#bidModal').close());

// page-specific binds
if(page==='dashboard'){ $('#claimDaily')?.addEventListener('click',()=>{if(state.lastDaily===today())return;state.lastDaily=today();state.money+=5;state.xp+=8;save()}); $('#dailyWheel')?.addEventListener('click',()=>{if(state.lastWheel===today())return;state.lastWheel=today();state.money+=[2,5,8,12,20][Math.floor(rnd(0,5))];save()}); }
if(page==='clicker'){ const active=new Set(); $('#moneyClick')?.addEventListener('pointerdown',e=>{active.add(e.pointerId);state.money+=state.perClick;state.xp+=1.5;state.streak++;state.loyalty++;levelUp();save()}); $('#moneyClick')?.addEventListener('pointerup',e=>active.delete(e.pointerId)); $$('.upgrade').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.upg,c={click:8+state.perClick*6,auto:20+state.auto*14,luck:40+state.luck*24}[k];if(state.money<c)return;state.money-=c;if(k==='click')state.perClick+=.2;if(k==='auto')state.auto+=.1;if(k==='luck')state.luck+=.04;save()})); $('#redeemLoyalty')?.addEventListener('click',()=>{if(state.loyalty<100)return;state.loyalty-=100;state.money+=8;save()}); $$('.loyalty-shop').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.dataset.item,cost={violet:150,neon:200,dense:120}[item];if(state.loyalty<cost)return;state.loyalty-=cost;state.themeMods[item]=true;save()})); }
if(page==='casino'){ $('#gameSelect').value=state.casino.game||'Blackjack'; $('#gameSelect').addEventListener('change',buildCasinoUI); $('#playGame').addEventListener('click',playCasino); }
if(page==='battles'){ $('#startBattle')?.addEventListener('click',()=>{const c=cases.find(x=>x.name===$('#battleCase').value);if(!c||state.money<c.price)return;state.money-=c.price;const y=makeSkin(c),o=makeSkin(c),win=y.value>=o.value;if(win)state.money+=y.value+o.value;state.inventory.push(y);$('#battleOutput').textContent=`${$('#battleMode').value}: ${win?'Win':'Loss'} ${m(y.value)} vs ${m(o.value)}`;save()}); }
if(page==='inventory'){ $('#sortValue')?.addEventListener('click',()=>{state.sortByValue=!state.sortByValue;save()}); $('#rarityFilter')?.addEventListener('change',renderPage); $('#searchSkin')?.addEventListener('input',renderPage); $('#autoSell')?.addEventListener('click',()=>{const keep=new Set(state.favorites);let sold=0;state.inventory=state.inventory.filter(i=>{if(keep.has(i.id))return true;sold+=i.value;return false});state.money+=sold;save()}); }

setInterval(()=>{state.money+=state.auto*state.perClick;const t=state.market.at(-1)+rnd(-1.8,2.2);state.market.push(Math.max(90,Math.min(130,t)));state.market=state.market.slice(-45);if(Math.random()>.83)state.listings.unshift({name:`${guns[Math.floor(rnd(0,guns.length))]} | ${patterns[Math.floor(rnd(0,patterns.length))]}`,price:+rnd(1.5,22).toFixed(2),type:Math.random()>.5?'listing':'auction'});state.listings=state.listings.slice(0,18);state.eventTick++;if(state.eventTick>35){state.eventTick=0;state.event=Math.random()>.55?'None':['Christmas','Halloween','Summer Heat'][Math.floor(rnd(0,3))]}crashTick();save()},3000);

renderCommon();renderPage();
